//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursoAspPlatzi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CRUDDBEntities : DbContext
    {
        public CRUDDBEntities()
            : base("name=CRUDDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CONTACTO> CONTACTO { get; set; }
    
        public virtual int SP_ELIMINAR(Nullable<int> iDCONTACTO)
        {
            var iDCONTACTOParameter = iDCONTACTO.HasValue ?
                new ObjectParameter("IDCONTACTO", iDCONTACTO) :
                new ObjectParameter("IDCONTACTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ELIMINAR", iDCONTACTOParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_Result> SP_LISTAR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_Result>("SP_LISTAR");
        }
    
        public virtual ObjectResult<SP_OBTENER_CONTACTO_Result> SP_OBTENER_CONTACTO(Nullable<int> iDCONTACTO)
        {
            var iDCONTACTOParameter = iDCONTACTO.HasValue ?
                new ObjectParameter("IDCONTACTO", iDCONTACTO) :
                new ObjectParameter("IDCONTACTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_OBTENER_CONTACTO_Result>("SP_OBTENER_CONTACTO", iDCONTACTOParameter);
        }
    
        public virtual int SP_UPDATE_CONTACTO(Nullable<int> iDCONTACTO, string nOMBRE, string tELEFONO, string cORREO)
        {
            var iDCONTACTOParameter = iDCONTACTO.HasValue ?
                new ObjectParameter("IDCONTACTO", iDCONTACTO) :
                new ObjectParameter("IDCONTACTO", typeof(int));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATE_CONTACTO", iDCONTACTOParameter, nOMBREParameter, tELEFONOParameter, cORREOParameter);
        }
    }
}
